//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     TextTransform Collider.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Mathematics;

namespace Latios.PhysicsEngine
{
    public unsafe partial struct Collider : IComponentData
    {
        #region TypeCasting
        public unsafe static implicit operator Collider(SphereCollider sphereCollider)
        {
            Collider collider = default;
            collider.m_type   = ColliderType.Sphere;
            collider.m_sphere = sphereCollider;
            return collider;
        }

        public unsafe static implicit operator SphereCollider(Collider collider)
        {
            CheckColliderIsCastTargetType(collider, ColliderType.Sphere);
            return collider.m_sphere;
        }

        public unsafe static implicit operator Collider(CapsuleCollider capsuleCollider)
        {
            Collider collider  = default;
            collider.m_type    = ColliderType.Capsule;
            collider.m_capsule = capsuleCollider;
            return collider;
        }

        public unsafe static implicit operator CapsuleCollider(Collider collider)
        {
            CheckColliderIsCastTargetType(collider, ColliderType.Capsule);
            return collider.m_capsule;
        }

        public unsafe static implicit operator Collider(CompoundCollider compoundCollider)
        {
            Collider collider      = default;
            collider.m_type        = ColliderType.Compound;
            collider.m_storage.a.x = compoundCollider.scale;
            collider.m_blobRef     = compoundCollider.compoundColliderBlob;
            return collider;
        }

        public unsafe static implicit operator CompoundCollider(Collider collider)
        {
            CheckColliderIsCastTargetType(collider, ColliderType.Compound);
            return new CompoundCollider(collider.m_blobRef, collider.m_storage.a.x);
        }

        [Conditional("ENABLE_UNITY_COLLECTIONS_CHECKS")]
        static void CheckColliderIsCastTargetType(Collider c, ColliderType targetType)
        {
            if (c.m_type != targetType)
            {
                switch (targetType)
                {
                    case ColliderType.Sphere: throw new InvalidOperationException("Collider is not a SphereCollider but is being casted to one.");
                    case ColliderType.Capsule: throw new InvalidOperationException("Collider is not a CapsuleCollider but is being casted to one.");
                    case ColliderType.Compound: throw new InvalidOperationException("Collider is not a CompoundCollider but is being casted to one.");
                }
            }
        }

        #endregion TypeCasting
    }
}

