using System;
using Unity.Collections;
using Unity.Entities;

namespace Latios.Calligraphics
{
    /// <summary>
    /// A description of a font face that can be loaded. It may be a system font, a streaming asset font, or a filesystem font at runtime.
    /// This is normally automatically generated by a FontCollectionAsset. However, you can generate your own at runtime if required.
    /// </summary>
    [Serializable]
    public struct FontLoadDescription : IEquatable<FontLoadDescription>
    {
        /// <summary>
        /// The file path for a streaming asset or filesystem font. For streaming assets, this relative to the streaming asset folder.
        /// This is the project path for system fonts, and is otherwise ignored.
        /// </summary>
        public FixedString512Bytes filePath;
        /// <summary>
        /// True if this is a streaming asset file.
        /// </summary>
        public bool streamingAssetLocationValidated;
        /// <summary>
        /// True if this is a system font file.
        /// </summary>
        public bool isSystemFont;
        /// <summary>
        /// If the file contains multiple faces, then this is the index of the face within the file.
        /// </summary>
        public int faceIndexInFile;

        //face Information
        public FixedString128Bytes fontFamily;
        public FixedString128Bytes fontSubFamily;
        public FixedString128Bytes typographicFamily;
        public FixedString128Bytes typographicSubfamily;
        public float               defaultWeight;
        public float               defaultWidth;
        public bool                isItalic;
        public float               slant;
        public readonly FontLookupKey fontLookupKey => new FontLookupKey(fontFamily, typographicFamily, defaultWeight, defaultWidth, isItalic, slant);

        /// <summary>
        /// Gets the FontLoadDescriptions for the font file at the specified runtime path, using the English name strings.
        /// </summary>
        /// <param name="path">The filepath of the font file</param>
        /// <param name="descriptionsToAppendTo">A list to append the results to</param>
        public static void GetDescriptionsFromPath(string path, ref NativeList<FontLoadDescription> descriptionsToAppendTo)
        {
            int startIndex = descriptionsToAppendTo.Length;
            // The language is used to get a localized string, if the font has one.
            // For consistency, we always want to use the same values, so we pick English.
            TextHelper.GetFontInfo(path, true, HarfBuzz.Language.English, descriptionsToAppendTo);
            for (int i = startIndex; i < descriptionsToAppendTo.Length; i++)
                descriptionsToAppendTo.ElementAt(i).isSystemFont = false;
        }

        public override bool Equals(object obj)
        {
            if (obj is FontLoadDescription item)
            {
                return Equals(item);
            }
            return false;
        }
        bool IEquatable<FontLoadDescription>.Equals(FontLoadDescription other)
        {
            return fontLookupKey == other.fontLookupKey;
        }
        public override int GetHashCode()
        {
             return fontLookupKey.GetHashCode();
        }

        public static bool operator ==(FontLoadDescription target, FontLoadDescription other) {
            return target.Equals(other);
        }
        public static bool operator !=(FontLoadDescription target, FontLoadDescription other) {
            return !target.Equals(other);
        }
        public override string ToString()
        {
            if (typographicFamily != "")
                return $"{fontFamily} - {fontSubFamily} (typographic: {typographicFamily} - {typographicSubfamily})";
            else
                return $"{fontFamily} - {fontSubFamily}";
        }
    }

    /// <summary>
    /// A collection of FontLoadDescriptions stored in a blob asset for loading.
    /// </summary>
    public struct FontLoadDescriptionsBlob
    {
        /// <summary>
        /// The array of FontLoadDescriptions to load
        /// </summary>
        public BlobArray<FontLoadDescription> descriptions;
        /// <summary>
        /// An optional name for a FontCollectionAsset that this blob was created from, if it was created from one.
        /// This value is only used for debugging purposes.
        /// </summary>
        public FixedString128Bytes collectionAssetName;
    }

    /// <summary>
    /// A set of fonts that should be loaded at runtime. Once a font is loaded, it is never unloaded.
    /// </summary>
    public struct FontLoadDescriptionsBlobReference : IComponentData
    {
        public BlobAssetReference<FontLoadDescriptionsBlob> blob;
    }
}

