// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CopyBytes

uniform ByteAddressBuffer _src;
uniform RWByteAddressBuffer _dst;

int _start;

// Todo: What is the nominal value per platform?
[numthreads(64, 1, 1)]
void CopyBytes(uint3 id : SV_DispatchThreadID)
{
    int index = _start + id.x;
    uint4 data = _src.Load4(index);
    _dst.Store4(index, data);
}
