using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

namespace Latios.Myri.InternalSourceGen
{
    // Make public on release
    internal static unsafe class StaticAPI
    {
        public interface IEffectSourceGenerated
        {
            // Must implement the following:
            // public static FunctionPointer<BurstDispatchEffectDelegate> GetBurstDispatchFunctionPtr();
            // That method should be generated by source generators which we grab via reflection.
        }

        public delegate void BurstDispatchEffectDelegate(void* context, int operation);

        public static void BurstDispatchEffect<TEffect, TParameters>(void* context, int operation)
            where TEffect : unmanaged, DSP.IEffect<TEffect, TParameters>
            where TParameters : unmanaged, IEffectParameters<TEffect, TParameters>
        {
            //
        }

        public interface ISpatialEffectSourceGenerated
        {
            // Must implement the following:
            // public static FunctionPointer<BurstDispatchSpatialEffectDelegate> GetBurstDispatchFunctionPtr();
            // That method should be generated by source generators which we grab via reflection.
        }

        public delegate void BurstDispatchSpatialEffectDelegate(void* context, int operation);

        public static void BurstDispatchSpatialEffect<TEffect, TParameters>(void* context, int operation)
            where TEffect : unmanaged, DSP.ISpatialEffect<TEffect, TParameters>
            where TParameters : unmanaged, ISpatialEffectParamaters<TEffect, TParameters>
        {
            //
        }
    }
}

